# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_user',
            name='crm',
            field=models.CharField(default=1234567, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_user',
            name='birth_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor_user',
            name='validation_code',
            field=models.CharField(default='qwert123', max_length=50),
        ),
    ]
