# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_auto_20170531_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_user',
            name='crm',
            field=models.CharField(max_length=15),
        ),
    ]
