# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adm_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_code', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=70)),
                ('cnpj', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=70)),
                ('phones', models.CharField(max_length=30)),
                ('site', models.CharField(default='', max_length=50)),
                ('password_tryed', models.IntegerField(default=0)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=30)),
            ],
        ),
    ]
