# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adm_user',
            name='adm_father',
            field=models.IntegerField(default=1),
        ),
    ]
