# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_app', '0002_adm_user_adm_father'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_adm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_code', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('adm_father', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Pending_doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_code', models.CharField(max_length=50)),
                ('crm', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('adm_father', models.IntegerField(default=-1)),
            ],
        ),
        migrations.RemoveField(
            model_name='adm_user',
            name='validation_code',
        ),
    ]
