# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_app', '0004_auto_20170603_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionalidade',
            name='url',
            field=models.CharField(max_length=40),
        ),
    ]
